// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs5iLDNZL8krk9FJL62a525ZCMhSvWnDc',
    appId: '1:427117368599:web:efd512e1106e37febed352',
    messagingSenderId: '427117368599',
    projectId: 'foodshare-6e185',
    authDomain: 'foodshare-6e185.firebaseapp.com',
    storageBucket: 'foodshare-6e185.firebasestorage.app',
    measurementId: 'G-8E005CP24Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaaaBx9r-bKkkv_XhAK7Ut0tgbajdDC9M',
    appId: '1:427117368599:android:59d66f1a1b1f5792bed352',
    messagingSenderId: '427117368599',
    projectId: 'foodshare-6e185',
    storageBucket: 'foodshare-6e185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjmJFCBnoNA7FcVSuGa20AGrYQBFhFWoM',
    appId: '1:427117368599:ios:e662237fe4a27a0abed352',
    messagingSenderId: '427117368599',
    projectId: 'foodshare-6e185',
    storageBucket: 'foodshare-6e185.firebasestorage.app',
    iosBundleId: 'com.example.foodShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjmJFCBnoNA7FcVSuGa20AGrYQBFhFWoM',
    appId: '1:427117368599:ios:e662237fe4a27a0abed352',
    messagingSenderId: '427117368599',
    projectId: 'foodshare-6e185',
    storageBucket: 'foodshare-6e185.firebasestorage.app',
    iosBundleId: 'com.example.foodShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs5iLDNZL8krk9FJL62a525ZCMhSvWnDc',
    appId: '1:427117368599:web:0565d8d670266627bed352',
    messagingSenderId: '427117368599',
    projectId: 'foodshare-6e185',
    authDomain: 'foodshare-6e185.firebaseapp.com',
    storageBucket: 'foodshare-6e185.firebasestorage.app',
    measurementId: 'G-TZR2QTLVMP',
  );
}
